#!/bin/bash

# script written to already include multiple checks and not fail at the first one
everythingOK=true

# linting the bib file (defined in Makefile)
check_duplicates() {
	# werbos is a reprint, so ignore that one
	grep "DUPLICATE_ENTRY" | grep -v "werbos2005applicationsReprint"
}

check_months() {
	grep -n "month[ ]* =" GUTbib.bib | grep "= [{0-9]"
}

if ! tmpString="$(make lint_bib)" ; then
	echo ":::::::::::::::::::::::::"
	echo "the bib linter encountered the following error"
	echo ":::::::::::::::::::::::::"
	echo "$tmpString"
	everythingOK=false
elif echo "$tmpString" | check_duplicates >/dev/null; then
	echo ":::::::::::::::::::::::::"
	echo "no error, but duplicate entries:"
	echo "$tmpString" | check_duplicates
	echo ":::::::::::::::::::::::::"
	everythingOK=false
elif [ -n "$(check_months)" ]; then
	echo ":::::::::::::::::::::::::"
	echo "month problems"
	check_months
	echo ":::::::::::::::::::::::::"
	everythingOK=false
fi


if ! $everythingOK; then
	echo ":::::::::::::::::::::::::"
	echo "there was an error, if you want to commit nonetheless use 'git commit --no-verify'"
	exit 1
fi
